[package]
name = "rust_os_journey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.23" # Version newer than '0.9.23' does not support cargo bootimage
volatile = "0.2.6" # Newer version will require update to VGA buffer 'ScreenChar' implementation

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"